name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - release*
  paths:
    include:
    - /tools/install-powershell.sh
    - /tools/installpsh-amazonlinux.sh
    - /tools/installpsh-debian.sh
    - /tools/installpsh-osx.sh
    - /tools/installpsh-redhat.sh
    - /tools/installpsh-suse.sh
pr:
  branches:
    include:
    - master
    - release*
  paths:
    include:
    - /tools/install-powershell.sh
    - /tools/installpsh-amazonlinux.sh
    - /tools/installpsh-debian.sh
    - /tools/installpsh-osx.sh
    - /tools/installpsh-redhat.sh
    - /tools/installpsh-suse.sh

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1

resources:
- repo: self
  clean: true
phases:
- template: templates/install-ps-phase.yml
  parameters:
    scriptName: ./tools/install-powershell.sh
    jobName: InstallPowerShellUbuntu
    pool: Hosted Ubuntu 1604

- template: templates/install-ps-phase.yml
  parameters:
    scriptName: ./tools/install-powershell.sh
    jobName: InstallPowerShellMacOS
    pool: Hosted macOS
