name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - release*
  paths:
    include:
    - '*'
    exclude:
    - /tools/releaseBuild/**/*
    - /.vsts-ci/misc-analysis.yml
pr:
  branches:
    include:
    - master
    - release*
  paths:
    include:
    - '*'
    exclude:
    - /tools/releaseBuild/**/*
    - /.vsts-ci/misc-analysis.yml

variables:
  GIT_CONFIG_PARAMETERS: "'core.autocrlf=false'"
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

resources:
- repo: self
  clean: true

jobs:
- template: templates/ci-build.yml

- template: templates/windows-test.yml
  parameters:
    purpose: UnelevatedPesterTests
    tagSet: CI
    parentJobs:
      - win_build

- template: templates/windows-test.yml
  parameters:
    purpose: ElevatedPesterTests
    tagSet: CI
    parentJobs:
      - win_build

- template: templates/windows-test.yml
  parameters:
    purpose: UnelevatedPesterTests
    tagSet: Others
    parentJobs:
      - win_build

- template: templates/windows-test.yml
  parameters:
    purpose: ElevatedPesterTests
    tagSet: Others
    parentJobs:
      - win_build

- template: templates/windows-packaging.yml

- job: verify_xunit
  displayName: Verify xUnit Results
  pool:
    name: 'Hosted VS2017'
  dependsOn:
    - win_build
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download build artifacts'
    inputs:
      downloadType: specific
      itemPattern: |
        xunit/**/*
      downloadPath: '$(System.ArtifactsDirectory)'

  - powershell: |
      dir "$(System.ArtifactsDirectory)\*" -Recurse
    displayName: 'Capture artifacts directory'
    continueOnError: true

  - powershell: |
      Import-Module .\tools\ci.psm1
      $xUnitTestResultsFile = "$(System.ArtifactsDirectory)\xunit\xUnitTestResults.xml"

      Test-XUnitTestResults -TestResultsFile $xUnitTestResultsFile
    displayName: Test
    condition: succeeded()
